version: "3.8"

services:
  # React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # - REACT_APP_FHIR_API_URL=${FHIR_API_URL}
      # - REACT_APP_AZURE_MAPS_KEY=${AZURE_MAPS_KEY}
      - REACT_APP_GRAPHHOPPER_URL=http://graphhopper:8989
    depends_on:
      - graphhopper
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network

  # GraphHopper routing engine with the specified configuration
  graphhopper:
    image: israelhikingmap/graphhopper:latest
    container_name: graphhopper
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - JAVA_OPTS=-Xmx6g -Xms6g
    volumes:
      - graphhopper_data:/data
      - osm_data:/osm_data
    command: >
      --url https://download.geofabrik.de/north-america/us/texas-latest.osm.pbf
      -o /data
      --host 0.0.0.0
    networks:
      - app-network

  # GraphQL API (placeholder - implement as needed)
  graphql:
    image: node:18-alpine
    command: "echo 'GraphQL service placeholder - implement as needed'"
    ports:
      - "4000:4000"
    volumes:
      - ./graphql:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  graphhopper_data:
  osm_data:
