apiVersion: 2019-12-01
name: nurse-scheduler-app
location: eastus
properties:
  containers:
    - name: nurse-scheduler
      properties:
        image: ${ACR_NAME}.azurecr.io/nurse-scheduler:${IMAGE_TAG}
        resources:
          requests:
            cpu: 1.0
            memoryInGB: 1.5
          limits:
            cpu: 2.0
            memoryInGB: 3.0
        ports:
        - port: 80
        env:
        - name: REACT_APP_FHIR_API_URL
          value: ${FHIR_API_URL}
        - name: REACT_APP_AZURE_MAPS_KEY
          value: ${AZURE_MAPS_KEY}
        - name: REACT_APP_GRAPHHOPPER_URL
          value: ${GRAPHHOPPER_URL}

    # GraphHopper container
    - name: graphhopper
      properties:
        image: graphhopper/graphhopper:latest
        resources:
          requests:
            cpu: 0.5
            memoryInGB: 1.5
          limits:
            cpu: 2.0
            memoryInGB: 4.0
        ports:
        - port: 8080
        env:
        - name: JAVA_OPTS
          value: -Xmx2g -Xms2g

    # GraphQL container
    - name: graphql
      properties:
        image: ${ACR_NAME}.azurecr.io/nurse-scheduler-graphql:${IMAGE_TAG}
        resources:
          requests:
            cpu: 0.5
            memoryInGB: 1.0
          limits:
            cpu: 1.0
            memoryInGB: 2.0
        ports:
        - port: 4000

  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
    - protocol: tcp
      port: 8080
    - protocol: tcp
      port: 4000
    dnsNameLabel: nurse-scheduler